### PR TITLE
Setup react router

### PR DESCRIPTION
**Pull request by avesk**
Issue: https://github.com/uvic-aero/dt-client/issues/1
# Overview
Sets up `react-router-dom` to handle routing between dt-client's component applications.
Creates some dummy component applications to demonstrate how routes will interact with our components.

### CODE REVIEW

**Review by KeeganCK — APPROVED** [review]

**Comment by dragonprevost** [comment]
Hey, I am getting a failed to compile error.
```
5:31:08 PM react.1    |  Failed to compile.
5:31:08 PM react.1    |  ./src/router.js
5:31:08 PM react.1    |  Module not found: Can't resolve 'TestHome' in '/Users/dragon/aero/dt-client/src'
```

Maybe those files didn't get added to your commit?

**Comment by avesk** [comment]
> Hey, I am getting a failed to compile error.
> 
> ```
> 5:31:08 PM react.1    |  Failed to compile.
> 5:31:08 PM react.1    |  ./src/router.js
> 5:31:08 PM react.1    |  Module not found: Can't resolve 'TestHome' in '/Users/dragon/aero/dt-client/src'
> ```
> 
> Maybe those files didn't get added to your commit?

Ah yes, should be up now

**Comment by dragonprevost** [comment]
> > Hey, I am getting a failed to compile error.
> > ```
> > 5:31:08 PM react.1    |  Failed to compile.
> > 5:31:08 PM react.1    |  ./src/router.js
> > 5:31:08 PM react.1    |  Module not found: Can't resolve 'TestHome' in '/Users/dragon/aero/dt-client/src'
> > ```
> > 
> > 
> > Maybe those files didn't get added to your commit?
> 
> Ah yes, should be up now

That solved the issue I was having. I am finding that the application takes a really long time to start up and gets hung up between these two outputs.
```
9:00:30 PM react.1    |  Browserslist: caniuse-lite is outdated. Please run next command `npm update`
9:01:06 PM react.1    |  Compiled successfully!
```
Has typescript been installed on this project?

**Review by dragonprevost — APPROVED** [review]

**Comment by avesk** [comment]
> > > Hey, I am getting a failed to compile error.
> > > ```
> > > 5:31:08 PM react.1    |  Failed to compile.
> > > 5:31:08 PM react.1    |  ./src/router.js
> > > 5:31:08 PM react.1    |  Module not found: Can't resolve 'TestHome' in '/Users/dragon/aero/dt-client/src'
> > > ```
> > > 
> > > 
> > > Maybe those files didn't get added to your commit?
> > 
> > 
> > Ah yes, should be up now
> 
> That solved the issue I was having. I am finding that the application takes a really long time to start up and gets hung up between these two outputs.
> 
> ```
> 9:00:30 PM react.1    |  Browserslist: caniuse-lite is outdated. Please run next command `npm update`
> 9:01:06 PM react.1    |  Compiled successfully!
> ```
> 
> Has typescript been installed on this project?

I am also getting hung up on that line.. Typescript has not been installed no. We're you thinking that it could be causing issues, or we're you thinking it would solve issues?

I'm gonna go ahead and merge this and open up a ticket for investigating this.

**Pull request merged**
